[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["pauliesnug"]
edition = "2021"
homepage = "https://github.com/pulseflow/workers"
repository = "https://github.com/pulseflow/workers"
readme = "README.md"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls-native-roots"] }
sha1_smol = { version = "1.0.0", features = ["std"] }

bytes = "1.6"
thiserror = "1.0"
cfg-if = "1.0.0"
futures = "0.3.30"
http = "1.1"
serde_json = "1.0"
lazy_static = "1.4"
