[package]
name = "pulseworker"
version = "0.1.0"
publish = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[[bin]]
name = "pulseworker"
path = "src/main.rs"

[dependencies]


[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["pauliesnug"]
edition = "2021"
homepage = "https://github.com/pulseflow/workers"
repository = "https://github.com/pulseflow/workers"
readme = "README.md"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.34", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
sha1 = { version = "0.6", features = ["std"] }

bytes = "1.1"
thiserror = "1.0"
cfg-if = "0.1"
futures = "0.3"
http = "0.2"
serde_json = "1.0"
lazy_static = "1.4"
